name: Flowers By Sam
favicon: null
layout_spectrum: 0.15710312547162175
typography_spectrum: 0.5889124106615782
title: 'Floral Design for Weddings, Events and Special Occasion Arrangements'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060405'
    - '#fdfdfd'
    - '#596750'
    - '#8fb784'
    - '#ff9d5b'
  brandStrength: 0.9715607727412134
  lightness: 0.4365359558723867
  saturation: 0
  rhythmicContrast: 0.8305927822366357
purpose: []
